### ISSUE TITLE
Samples app fails with java.lang.OutOfMemoryError: Metaspace

### ISSUE THREAD

**Issue by ekcasey** [paketo-buildpacks/leiningen#39]
## What happened?
With the default configuration the [leiningen sample app](https://github.com/paketo-buildpacks/samples/tree/main/java/leiningen) fails with an out of memory error.

* What were you attempting to do?
In `paketo-buildpacks/samples/java/leiningen":
```
pack build samples/lein --builder paketobuildpacks/builder:base
```
```
docker run --rm --tty --publish 8080:8080 samples/lein
```

* What did you expect to happen?
The container to start and the application to be available on port 8080

* What was the actual behavior? Please provide log output, if possible.

```
Resource exhaustion event.
ResourceExhausted! (1/0)
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: Syntax error compiling at (io/pedestal/http/jetty.clj:1:1).
	at clojure.lang.Compiler.load(Compiler.java:7648)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:459)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__1738.invoke(core.clj:6126)
	at clojure.core$load.invokeStatic(core.clj:6125)
	at clojure.core$load.doInvoke(core.clj:6109)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5908)
	at clojure.core$load_one.invoke(core.clj:5903)
	at clojure.core$load_lib$fn__1679.invoke(core.clj:5948)
	at clojure.core$load_lib.invokeStatic(core.clj:5947)
	at clojure.core$load_lib.doInvoke(core.clj:5928)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at clojure.core$load_libs.invokeStatic(core.clj:5986)
	at clojure.core$load_libs.doInvoke(core.clj:5969)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at clojure.core$require.invokeStatic(core.clj:6071)
	at clojure.core$require.doInvoke(core.clj:6007)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at io.pedestal.http$server.invokeStatic(http.clj:346)
	at io.pedestal.http$server.invoke(http.clj:335)
	at io.pedestal.http$create_server.invokeStatic(http.clj:377)
	at io.pedestal.http$create_server.invoke(http.clj:357)
	at io.pedestal.http$create_server.invokeStatic(http.clj:374)
	at io.pedestal.http$create_server.invoke(http.clj:357)
	at lein_source.server$eval24587.invokeStatic(server.clj:7)
	at lein_source.server$eval24587.invoke(server.clj:7)
	at clojure.lang.Compiler.eval(Compiler.java:7177)
	at clojure.lang.Compiler.load(Compiler.java:7636)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:459)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__1738.invoke(core.clj:6126)
	at clojure.core$load.invokeStatic(core.clj:6125)
	at clojure.core$load.doInvoke(core.clj:6109)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:384)
	at clojure.lang.Util.loadWithClass(Util.java:251)
	at lein_source.server.<clinit>(Unknown Source)
Caused by: java.lang.OutOfMemoryError: Metaspace
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
	at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
	at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
	at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
	at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(Unknown Source)
ERROR: HeapHistogram action failed: JVMTI GetClassSignature failed: 112
```

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.

```
> pack version
0.16.0+git-e0f6c50.build-1898
```

* What buildpacks are you using? Please include versions.

```
> pack inspect-image samples/lein
Inspecting image: samples/lein

REMOTE:
(not present)

LOCAL:

Stack: io.buildpacks.stacks.bionic

Base Image:
  Reference: 7caf66d362029ff87d6667a7d28f64b64e7ffc44770dd109a0926352470748c7
  Top Layer: sha256:aaebbe2c9378b9aeb1aee186543c10940c04f18188930f62670ffb3591c4a5a8

Run Images:
  index.docker.io/paketobuildpacks/run:base-cnb
  gcr.io/paketo-buildpacks/run:base-cnb

Buildpacks:
  ID                                         VERSION
  paketo-buildpacks/ca-certificates          1.0.1
  paketo-buildpacks/bellsoft-liberica        6.2.0
  paketo-buildpacks/leiningen                1.2.1
  paketo-buildpacks/executable-jar           3.1.3
  paketo-buildpacks/apache-tomcat            3.2.0
  paketo-buildpacks/dist-zip                 2.2.2
  paketo-buildpacks/spring-boot              3.5.0

Processes:
  TYPE                  SHELL        COMMAND        ARGS
  web (default)         bash         java           lein_source.server
  executable-jar        bash         java           lein_source.server
  task                  bash         java           lein_source.server
  ```

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?
  
`paketobuildpacks/builder:base`

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?
N/A

## Checklist

* [x] I have included log output.
* [x] The log output includes an error message.
* [x] I have included steps for reproduction.

**Comment by eddumelendez** [comment]
Just for the record, this is only happening when is running using java 11. The workaround is to increase the metaspace `docker run -p 8080:8080 -e JAVA_OPTS="-XX:MaxMetaspaceSize=104744K" samples/lein`. When is built using java 8 `pack build samples/lein --builder paketobuildpacks/builder:base -e 'BP_JVM_VERSION=8.*'` there is no error when the container is running.

**Comment by dmikusa-pivotal** [comment]
I just updated the command to run the sample in the README to include setting a higher metaspace. This was already being done in our CI tests for the sample repo.

https://github.com/paketo-buildpacks/samples/pull/103

**Comment by ekcasey** [comment]
Would it be worth having the buildpack contribute a runtime environment variable to increase the metaspace to avoid this issue?

**Comment by dmikusa-pivotal** [comment]
I think that would be difficult or require some feature work. In this buildpack, you can't just overwrite the value because it's generated by the memory calculator and depends on the app pushed. You'd need a way to influence the memory calculator's decision. There are a few flags to override decisions made by the memory calculator, but I think those are intended for users so a user can have total control. As far as I know, there's not really a way to ask the memory calculator to still make its decision but adjust them based on some factors contributed by other buildpacks. 

I think it would be helpful to have controls like that. Let's say you have an agent that gets installed and you know it generally requires 10% more heap space when enabled, the agent should be able to specify that in some way. I can create a new issue for that if it seems reasonable.
